### ISSUE TITLE
ADD PAPER: word2vec

### ISSUE THREAD

**Issue by AmgadHasan** [EdoPedrocchi/RicercaMente#9]

**Comment by EdoPedrocchi** [comment]
GO!

**Comment by AmgadHasan** [comment]
Dump resources here; will create a pr soon

https://arxiv.org/abs/1301.3781

https://en.m.wikipedia.org/wiki/Word2vec

https://www.tensorflow.org/text/tutorials/word2vec

**Comment by EdoPedrocchi** [comment]
Cool!!

**Comment by AmgadHasan** [comment]
Created pr
https://github.com/EdoPedrocchi/RicercaMente/pull/21
